/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mapROM_20 (
    input [2:0] select,
    output reg [95:0] out
  );
  
  
  
  localparam MAPS = 480'h045105151041110104540514114105040051141401010454051411151441045505441105051501151544145511511545155511541545044505511515;
  
  always @* begin
    out = MAPS[(select)*96+95-:96];
  end
endmodule
