/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module playerLED_7 (
    input clk,
    input rst,
    input [15:0] sequence,
    output reg [143:0] led_sequence
  );
  
  
  
  localparam B = 24'hff0000;
  
  localparam BLANK = 24'h000000;
  
  reg rst_n;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst;
    rst_n = M_reset_cond_out;
    
    case (sequence[0+0-:1])
      1'h0: begin
        led_sequence[0+23-:24] = 24'h000000;
      end
      1'h1: begin
        led_sequence[0+23-:24] = 24'hff0000;
      end
      default: begin
        led_sequence[0+23-:24] = 24'h000000;
      end
    endcase
    
    case (sequence[1+0-:1])
      1'h0: begin
        led_sequence[24+23-:24] = 24'h000000;
      end
      1'h1: begin
        led_sequence[24+23-:24] = 24'hff0000;
      end
      default: begin
        led_sequence[24+23-:24] = 24'h000000;
      end
    endcase
    
    case (sequence[2+0-:1])
      1'h0: begin
        led_sequence[48+23-:24] = 24'h000000;
      end
      1'h1: begin
        led_sequence[48+23-:24] = 24'hff0000;
      end
      default: begin
        led_sequence[48+23-:24] = 24'h000000;
      end
    endcase
    
    case (sequence[3+0-:1])
      1'h0: begin
        led_sequence[72+23-:24] = 24'h000000;
      end
      1'h1: begin
        led_sequence[72+23-:24] = 24'hff0000;
      end
      default: begin
        led_sequence[72+23-:24] = 24'h000000;
      end
    endcase
    
    case (sequence[4+0-:1])
      1'h0: begin
        led_sequence[96+23-:24] = 24'h000000;
      end
      1'h1: begin
        led_sequence[96+23-:24] = 24'hff0000;
      end
      default: begin
        led_sequence[96+23-:24] = 24'h000000;
      end
    endcase
    
    case (sequence[5+0-:1])
      1'h0: begin
        led_sequence[120+23-:24] = 24'h000000;
      end
      1'h1: begin
        led_sequence[120+23-:24] = 24'hff0000;
      end
      default: begin
        led_sequence[120+23-:24] = 24'h000000;
      end
    endcase
  end
endmodule
