set projDir "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/vivado"
set projName "GameMap"
set topName top
set device xc7a35tftg256-1
if {[file exists "$projDir/$projName"]} { file delete -force "$projDir/$projName" }
create_project $projName "$projDir/$projName" -part $device
set_property design_mode RTL [get_filesets sources_1]
set verilogSources [list "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/au_top_0.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/reset_conditioner_1.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/edge_detector_2.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/button_conditioner_3.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/beta_4.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/multi_seven_seg_5.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/initialise_col_LED_6.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/initialise_player_LED_7.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/ws2812b_writer_8.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/ws2812b_writer_9.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/pipeline_10.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/alu_11.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/mapROM_12.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/regfile_13.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/counter_14.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/game_CU_15.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/counter_16.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/seven_seg_17.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/decoder_18.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/adder_19.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/boolean_20.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/shifter_21.v" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/verilog/compare_22.v" ]
import_files -fileset [get_filesets sources_1] -force -norecurse $verilogSources
set xdcSources [list "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/constraint/alchitry.xdc" "C:/Users/zhiyi/Desktop/1D-Computation-Structures-main/1D-Computation-Structures-main/ObstacleGame/work/constraint/custom.xdc" "C:/Program\ Files/Alchitry/Alchitry\ Labs/library/components/au.xdc" ]
read_xdc $xdcSources
set_property STEPS.WRITE_BITSTREAM.ARGS.BIN_FILE true [get_runs impl_1]
update_compile_order -fileset sources_1
launch_runs -runs synth_1 -jobs 8
wait_on_run synth_1
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1
