/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module store_value_4 (
    input btna,
    input btnb,
    input rst,
    input clk,
    input [15:0] switch,
    output reg [15:0] getA,
    output reg [15:0] getB
  );
  
  
  
  wire [1-1:0] M_detectA_out;
  reg [1-1:0] M_detectA_in;
  edge_detector_13 detectA (
    .clk(clk),
    .in(M_detectA_in),
    .out(M_detectA_out)
  );
  
  wire [1-1:0] M_detectB_out;
  reg [1-1:0] M_detectB_in;
  edge_detector_13 detectB (
    .clk(clk),
    .in(M_detectB_in),
    .out(M_detectB_out)
  );
  
  wire [1-1:0] M_conda_out;
  button_conditioner_14 conda (
    .clk(clk),
    .in(btna),
    .out(M_conda_out)
  );
  
  wire [1-1:0] M_condb_out;
  button_conditioner_14 condb (
    .clk(clk),
    .in(btnb),
    .out(M_condb_out)
  );
  
  reg [15:0] M_a_d, M_a_q = 1'h0;
  
  reg [15:0] M_b_d, M_b_q = 1'h0;
  
  always @* begin
    M_a_d = M_a_q;
    M_b_d = M_b_q;
    
    M_detectA_in = M_conda_out;
    M_detectB_in = M_condb_out;
    if (M_detectA_out) begin
      M_a_d = switch;
    end
    if (M_detectB_out) begin
      M_b_d = switch;
    end
    getA = M_a_q;
    getB = M_b_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_a_q <= 1'h0;
    end else begin
      M_a_q <= M_a_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_b_q <= 1'h0;
    end else begin
      M_b_q <= M_b_d;
    end
  end
  
endmodule
